website/app.py
from flask import Flask

from website.blueprints.page import page
from website.extensions import debug_toolbar

def create_app():
    """
    Create a Flask application

    :return: Flask app
    """
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object('config.settings')
    app.config.from_pyfile('settings.py', silent=True)

    app.register_blueprint(page)
    extensions(app)

    return app


def extensions(app):
    """
    Register extensions

    :param app: Flask app instance
    :return: None
    """
    debug_toolbar.init_app(app)

    return None

website/blueprints/page/__init__.py
from website.blueprints.page.views import page

website/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')


@page.route('/about')
def about():
    return render_template('page/about.html')


@page.route('/services')
def services():
    return render_template('page/services.html')


@page.route('/contact')
def contact():
    return render_template('page/contact.html')

website/templates/layouts/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('page.home') }}">My Website</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('page.home') }}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('page.about') }}">About
              <span class="sr-only">(current)</span>
            </a>
          </li>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('page.services') }}">Services
              <span class="sr-only">(current)</span>
            </a>
          </li>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('page.contact') }}">Contact
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">{% block heading %}{% endblock %}</h1>
        <p class="lead">{% block body %}{% endblock %}</p>
      </div>
    </div>
  </div>

  <!-- Footer-->
  <body class="d-flex flex-column">
    <div id="page-content">
      <div class="container text-center">
        <div class="row justify-content-center">
          <div class="col-md-1">
            <h1 class="font-weight-light mt-4 text-white">Sticky Footer using Flexbox</h1>
            <p class="lead text-white-50">Use just two Bootstrap 4 utility classes and three custom CSS rules and you will have a flexbox enabled sticky footer for your website!</p>
          </div>
        </div>
      </div>
    </div>
    <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
      <div class="container text-center">
        <small>Copyright &copy; Your Website</small>
      </div>
    </footer>
  </body>


  <!-- Bootstrap core JavaScript -->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.slim.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

</body>

</html>